// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Database_Example
{
    public partial class Director
    {
        public Director()
        {
            Movie = new HashSet<Movie>();
        }

        [Required]
        [Column("Director_Name")]
        [StringLength(150)]
        public string DirectorName { get; set; }
        [Key]
        [Column("Director_Id")]
        public int DirectorId { get; set; }

        [InverseProperty("Director")]
        public virtual ICollection<Movie> Movie { get; set; }

        public override string ToString()
        {
            return DirectorName;
        }
    }
}