// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Database_Example
{
    public partial class Movie
    {
        [Key]
        [Column("Movie_Id")]
        public int MovieId { get; set; }
        [Column("director_id")]
        public int DirectorId { get; set; }
        [Column("color")]
        [StringLength(150)]
        public string Color { get; set; }
        [Column("num_critic_for_reviews")]
        public int? NumCriticForReviews { get; set; }
        [Column("duration")]
        public int? Duration { get; set; }
        [Column("director_facebook_likes")]
        public int? DirectorFacebookLikes { get; set; }
        [Column("actor_3_facebook_likes")]
        public int? Actor3FacebookLikes { get; set; }
        [Column("actor_2_name")]
        [StringLength(150)]
        public string Actor2Name { get; set; }
        [Column("actor_1_facebook_likes")]
        public int? Actor1FacebookLikes { get; set; }
        [Column("gross")]
        public long? Gross { get; set; }
        [Column("genres")]
        [StringLength(150)]
        public string Genres { get; set; }
        [Column("actor_1_name")]
        [StringLength(150)]
        public string Actor1Name { get; set; }
        [Column("movie_title")]
        [StringLength(150)]
        public string MovieTitle { get; set; }
        [Column("num_voted_users")]
        public int? NumVotedUsers { get; set; }
        [Column("cast_total_facebook_likes")]
        public int? CastTotalFacebookLikes { get; set; }
        [Column("actor_3_name")]
        [StringLength(150)]
        public string Actor3Name { get; set; }
        [Column("facenumber_in_poster")]
        public int? FacenumberInPoster { get; set; }
        [Column("plot_keywords")]
        [StringLength(150)]
        public string PlotKeywords { get; set; }
        [Column("movie_imdb_link")]
        [StringLength(150)]
        public string MovieImdbLink { get; set; }
        [Column("num_user_for_reviews")]
        public int? NumUserForReviews { get; set; }
        [Column("language")]
        [StringLength(150)]
        public string Language { get; set; }
        [Column("country")]
        [StringLength(150)]
        public string Country { get; set; }
        [Column("content_rating")]
        [StringLength(150)]
        public string ContentRating { get; set; }
        [Column("budget")]
        public long? Budget { get; set; }
        [Column("title_year")]
        public int? TitleYear { get; set; }
        [Column("actor_2_facebook_likes")]
        public int? Actor2FacebookLikes { get; set; }
        [Column("imdb_score", TypeName = "decimal(10, 2)")]
        public decimal? ImdbScore { get; set; }
        [Column("aspect_ratio", TypeName = "decimal(10, 2)")]
        public decimal? AspectRatio { get; set; }
        [Column("movie_facebook_likes")]
        public int? MovieFacebookLikes { get; set; }

        [ForeignKey("DirectorId")]
        [InverseProperty("Movie")]
        public virtual Director Director { get; set; }

        public override string ToString()
        {
            return $"{MovieTitle} by {DirectorId}";
        }
    }
}